### PR TITLE
Added title gravity - appearence property

### PR DESCRIPTION
**Pull request by filwiesner**
Added title gravity property into SMSegment. It enables user to set position of title relatively to image.
Possible positions:
 -> right - default position
 -> bottom - title is below image
 -> top - title is on top of image
 -> left - title is on left of image

Following improvements and fixes caused by rework:
 - Fix: wrong title height in horizontal layouts
 - Fix: Shrink image if content doesnť fit If height of label (with applied font) and image is bigger then control height, shrink image to fit label. -> Helps on vertical organise mode

### CODE REVIEW

**Comment by filwiesner** [comment]
Hey,
here is my try to implement title position. What do you think @sima-11 ?

Here are some screenshots:
screen shot 2017-10-29 at 23 05 10

screen shot 2017-10-29 at 23 06 30



My previous issue about this: #38

**Comment by sima-11** [comment]
Hey @w00d3nl3g, just reviewed your implementation and felt happy with it. Have merged your code. Thank you for your support! :)

**Comment by filwiesner** [comment]
No problem dude. Will you bump the version?
And should I add documentation and screenshots to Readme? English is not my native language so I would rather leave it to you :)

**Comment by sima-11** [comment]
Hey @w00d3nl3g, just did a new release (v1.4). Will probably leave the Readme and screenshots to later, as I'll try to make some changes to the existing code as well (if I got some time).

**Pull request merged**
