### PR TITLE
More generic version of SMSegmentView and .podspec

### PR DESCRIPTION
**Pull request by michallaskowski**
Hi,
I was in a need for a customized Segmented Control, and found your project. Instead of creating a new one, I went for a small rewrite. I created SMBasicSegmentView and SMBasicSegment (the naming could be better, I was redoing it at late night;) - they are just basic views, more customizable and allow for greater visual control; just the basics for a segmented control to work. 
I remade your classes to inherit from the basic ones, so the demo didn't change except I added my own SMAlphaImageSegment, just for testing and showcase.
Also - a podspec file. A tag in repo would be nice, for better version control. Right now the pod is getting the source from master branch. But I will leave you to it.
If you have any questions, feel free to ask.
Cheers

### CODE REVIEW

**Comment by sima-11** [comment]
@michallaskowski Hi Michal, first of all, thanks for your support on this framework! This is what I hoped from contributors like you to make such a simple framework better. The second thing is that I'm currently spending all my time on another project, so will have to leave this one for a while.

I will go through your code and probably write you some comments at a later point.

Thanks again for your work!

Cheers,
Si

**Comment by hebertialmeida** [comment]
Any updates on this? Merge please.

**Comment by sima-11** [comment]
Hi @hebertialmeida @michallaskowski ,

Have merged the code. Just to let you know. :)

Cheers

**Comment by hebertialmeida** [comment]
@allenbryan11 Thanks!

**Pull request merged**
